services:
  keycloak:
    image: mthuwhihand/mms-keycloak:latest
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      REDIRECT_URL_DEFAULT: https://mms.vitrust.app
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped

volumes:
  keycloak_data:
